---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## Loading and preprocessing the data
```{r, echo = TRUE}
# Reading the file.
activity <- read.csv("activity.csv")

# Changing the date column's type to "Date"
activity$date <- as.Date(activity$date, format = "%Y-%m-%d")
```

## What is mean total number of steps taken per day?
```{r, echo = TRUE}
# Calculate the total number of steps taken per day
library(dplyr)
activityGroupedTotal <- activity %>% group_by(date) %>% 
  summarise(across(everything(), sum))
head(activityGroupedTotal)
```

```{r, echo = TRUE}
# Make a histogram of the total number of steps taken each day
hist(activityGroupedTotal$steps, main = "Histogram of total steps per day")
```

```{r, echo = TRUE}
# Calculate and report the mean and median of the total number of steps taken per day
cat("Mean of the total number of steps taken per day", mean(activityGroupedTotal$steps, na.rm = TRUE), "\n")

cat("Median of the total number of steps taken per day",
median(activityGroupedTotal$steps, na.rm = TRUE))

```


## What is the average daily activity pattern?
```{r, echo = TRUE}
# Make a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)
activityGroupedAverage <- activity %>% group_by(interval) %>% 
  summarise(steps = mean(steps, na.rm=TRUE))

plot(activityGroupedAverage$interval, activityGroupedAverage$steps, type = "l", xlab = "Interval", ylab = "Average Steps")

```

```{r, echo = TRUE}
# Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?

cat("Interval that contains maximum steps: ",
activityGroupedAverage[activityGroupedAverage$steps >= max(activityGroupedAverage$steps, na.rm = TRUE),]$interval, "\n")

cat("Steps: ",
max(activityGroupedAverage$steps, na.rm = TRUE))



```


## Imputing missing values
```{r, echo = TRUE}
# Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)
summary(activity)

```
```{r, echo = TRUE}
#Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.

#Create a new dataset that is equal to the original dataset but with the missing data filled in.
activity2 <- activity

# Filling the NAs with average of its interval in the new dataset.
for(i in 1:nrow(activity2)){
  ifelse(is.na(activity2[i,1]), activity2[i, 1] <- activityGroupedAverage[activityGroupedAverage$interval == activity2[i,3],]$steps, i)}

```

```{r, echo = TRUE}
# Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?
activity2GroupedTotal <- activity2 %>% group_by(date) %>% 
  summarise(across(everything(), sum))

hist(activity2GroupedTotal$steps, main = "Histogram of total steps per day in the new dataset")

```

```{r, echo = TRUE}
cat("Mean of the total number of steps taken per day in the new dataset", mean(activity2GroupedTotal$steps, na.rm = TRUE), "\n")

cat("Median of the total number of steps taken per day in the new dataset",
median(activity2GroupedTotal$steps, na.rm = TRUE), "\n")

```
### Median has changed in the new dataset compared to the original one

## Are there differences in activity patterns between weekdays and weekends?

```{r, echo = TRUE}
# Create a new factor variable in the dataset with two levels – “weekday” and “weekend” indicating whether a given date is a weekday or weekend day.
#weekdays1 <- c('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday')
#activity2$wDay <- factor((weekdays(activity2$date) %in% weekdays1), 
#         levels=c(FALSE, TRUE), labels=c('weekend', 'weekday'))

library(chron)
activity2$wDay <- factor(ifelse(is.weekend(activity2$date), "Weekend", "Weekday"))
```

```{r plot, echo=TRUE, warning=FALSE, include=TRUE, Tidy=TRUE, fig.keep = "all", fig.show = 'asis', fig.width = 10}
# Make a panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis).
activity2GroupedWeek <- activity2 %>% group_by(wDay, interval) %>% 
  summarise(steps = mean(steps))

library(ggplot2)
qplot(interval, steps, data = activity2GroupedWeek,
      facets = . ~ wDay,
      xlab = "Average Steps", ylab = "Interval",
      main = "A Comparison of Weekday and Weekend") + geom_line(aes(group = "1"), col = "black")

```